[profile.default]
src = 'src'
out = 'out'
solc_version = "0.8.20"
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
use_literal_content = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config